name: voxlens-stt
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - transformers
  - librosa
  - numpy
  - scipy
  - flask
  - pytest
  - jupyter
  - pandas
  - ffmpeg
  - pip
  - pip:
      - whisper
